export const TAG_OPTIONS = [
  "PersonalGrowth",
  "CareerDevelopment",
  "Technology",
  "HealthandWellness",
  "Finance",
  "Travel",
  "Food",
  "Sports",
  "Entertainment",
  "Education",
  "Business",
  "Marketing",
  "Programming",
  "Design",
  "Writing",
  "Art",
  "Music",
  "Movies",
  "SelfImprovement",
  "Spirituality",
  "Environment",
  "Fashion",
  "Beauty",
  "Fitness",
  "HomeDecor",
  "Gardening",
  "Cooking",
  "Photography",
  "DIY",
  "Other",
] as const;

export type TagOption = typeof TAG_OPTIONS[number];